import { NextResponse } from 'next/server';

export async function GET() {
    const products = [
        {
            id: 1,
            name: 'Nước Yến sào Đông trùng hạ thảo Nest100 - Có đường',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/nuoc-yen-sao-dong-trung-ha-thao-nest100-co-duong-1.webp',
            shop: 'GLOBAL (Yến Sào NEST100)',
            rating: 4.5,
            soldCount: 2386,
            price: 43000,
            originalPrice: null,
            discount: null,
        },
        {
            id: 2,
            name: 'Hạt điều rang muối loại 1 (còn vỏ lụa) Happy Nuts 500g',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/hat-dieu-rang-muoi-loai-1-con-vo-lua-happy-nuts-500g-1.webp',
            shop: 'STV Trading',
            rating: 4.5,
            soldCount: 782,
            price: 253800,
            originalPrice: 282000,
            discount: 10,
        },
        {
            id: 3,
            name: 'Bánh Trung Thu 2025 - Thu An Nhiên (bánh chay hộp 2 bánh 1 trà)',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/banh-trung-thu-2025-thu-an-nhien-banh-chay-hop-2-banh-1-tra-1.webp',
            shop: 'STV Trading',
            rating: 4.5,
            soldCount: 472,
            price: 110700,
            originalPrice: 369000,
            discount: 70,
        },
        {
            id: 4,
            name: 'Tấm lót giường Abena Pad (giặt được) 85x90cm',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/tam-lot-giuong-abena-pad-giat-duoc-85x90cm-1.webp',
            shop: 'STV Trading',
            rating: 4.5,
            soldCount: 193,
            price: 490000,
            originalPrice: null,
            discount: null,
        },
        {
            id: 5,
            name: 'Thực phẩm bảo vệ sức khoẻ ByeAlco (5 viên/vỉ)',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/thuc-pham-bao-ve-suc-khoe-byealco-5-vien-vi-1.webp',
            shop: 'CHẤT VIỆT GROUP',
            rating: 4.5,
            soldCount: 33100,
            price: 59500,
            originalPrice: null,
            discount: null,
        },
        {
            id: 6,
            name: 'Cà Phê Sâm Canada',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/ca-phe-sam-canada-1.webp',
            shop: 'CHẤT VIỆT GROUP',
            rating: 4.5,
            soldCount: 13600,
            price: 110000,
            originalPrice: null,
            discount: null,
        },
        {
            id: 7,
            name: 'Nước Yến sào Đông trùng hạ thảo Nest100 - Không đường',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/nuoc-yen-sao-dong-trung-ha-thao-nest100-co-duong-1.webp',
            shop: 'GLOBAL (Yến Sào NEST100)',
            rating: 4.5,
            soldCount: 1856,
            price: 43000,
            originalPrice: null,
            discount: null,
        },
        {
            id: 8,
            name: 'Hạt điều rang muối loại 1 Premium Happy Nuts 500g',
            image: 'https://sieuthivina.com/assets/client/images/thumbs/hat-dieu-rang-muoi-loai-1-con-vo-lua-happy-nuts-500g-1.webp',
            shop: 'STV Trading',
            rating: 4.5,
            soldCount: 654,
            price: 265000,
            originalPrice: 300000,
            discount: 12,
        },
    ];

    return NextResponse.json(products);
}
